### ISSUE TITLE
Pyra setup tool is crashing on Mb02

### ISSUE THREAD

**Issue by patrickjaigner** [tum-esm/pyra-setup-tool#4]
**Describe the bug**
Tried to downgrade to 4.0.6 from 4.0.7. The setup tool crashes at first input prompt "which python"

<img width="1172" alt="image" src="https://user-images.githubusercontent.com/59452158/219158318-a4225a18-8d65-4b09-ace6-1689a62a28be.png">

**Comment by dostuffthatmatters** [comment]
This was already fixed in https://github.com/tum-esm/pyra-setup-tool/commit/bdc61445276ff4b29a0e3200344deb86e75f3fc6. What was happening is that the `run_shell_command` function ran on the current working directory when not specified otherwise. This commit specifies it to use the setup-tool's directory by default.

**Comment by dostuffthatmatters** [comment]
When using old versions of the software, the "git pull" command only works when you are already inside the setup tool directory as specified in the docs: https://pyra.esm.ei.tum.de/docs/user-guide/setup#pyra-setup-tool

```bash
cd %userprofile%/Documents/pyra-setup-tool
python run.py
```
